apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  namespace: web-services
  annotations:
    cert-manager.io/cluster-issuer: thefoss-le-prod
    # NGINX Inc specific annotations
    nginx.org/websocket-services: "proxmox"
    nginx.org/ssl-services: "proxmox"
spec:
  ingressClassName: external
  tls:
    - hosts:
        - proxmox.thefoss.org
      secretName: proxmox-tls
  rules:
    - host: proxmox.thefoss.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox
                port:
                  number: 8006
