apiVersion: v1
kind: ConfigMap
metadata:
    name: nextcloud-configs
    namespace: nextcloud
data:
    values.yaml: ENC[AES256_GCM,data:gXem5foqYNlg3VF27lTCwRinFqduO5PXGUFLMUYgMSTht4it46tXBIrEKIeaCD3yUq0/QgoOEApwWU67P5TmxOxDrFwPkKbsG/cXL8+RijDwDAnAp557T+i5YDVGRukiuOPZMS1b8qF0giTvWukaUPj+VPm4zSzvyNW0/GcEfNLiG0Q3GP+Ld1AocOGLMKFtxTzX3C3ZL/PjwGGdlOIFpDAzkg0YuLeVqkVGyE1VVobS9QMyTheRkmtCPTbhOYTkonEzWXOJ1HnfrhzHHF1NY7fMFEKTI16Egc2T4G4tE8Jvn7EEjUA45tY3DhwFevktuZKqDqcbIB1zz4ZNZuXKSG9yzKoLS2hlvg+K3g4MZfc6mbq2jGh1wcoCVQc4STrkAApvQmHLx3ZeNQx1to2Jcj6ELs08aPri2LdrsBTMZr37KqP3uMxZ+dtO+/PszmZ9pmBzu/kJECcPbCHAZcj8WLG/E7EfV4m0HNUlq0peH8iYQGAp4H3KwXH/q5Zqsm48jSQbANYpp3q9Ijndp/mc+9hZ+01Mhvdd5/7t8jaOf5a7smQjju1IarCnh36RjRVapmk+hO6ecdV6GFwVwhx26+/P7l7ZsX0scm8mdgYcFW1UuU6iH8wL+9CDMnbpoHJwbK9ovz4JxEpTK6MVZBcLtXHywQ1Aly9NutduD9recEFRlp2VF4O+us6GO2wNIoHziBH01mQWVYTV0t9LNeLmuSGntDz9hYBXwiQJX3NXV4se0ubzWz5oScCutMrCBkJ4gFt7TWYdvtvSFHWbCSaYyljEefVPQR68tH5eVr0Aawq3S0XkWX7YchLK0TYSfIwmo5y1Q5+WyOcwuMudvAG5H+6Nj1IsOJdrHkNqoneDXh65UxjCKeXMh4APcY+qD9RhBmHd84YoDWwX9sWas99+J0X3aKz+C3VkRFx092zETDbvhPnkg9iNdbqye+HjJB2fsrlFfTytd41xgmAe72DmVzIHheRt7jYGZsuQZBXKoUwXSlkw6luXCJta6gD11S8EYUG0qC3KDUBYs8eglrbDPzG145pUeQ0fCfqpSi18J03Sc++C00Pbk7/aLf6zsMoCfsKnD4/gcnGWKiKVbyI0Rm78C4FVfE7Vrzs1,iv:ljs3ny3Z5oGNKw/NfrmC01nBw2C/jkiVO1UtCvFNbvo=,tag:jfHpW/7e5LeU4zdglUf1QQ==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGJmQlc0YjZsN1hJSmdL
            T0wwbWk0WkxWVVdxRVo5dW1CYkVHSzU2bHl3Ck10ZlRTdkNsNDFLb0JYNDVJQmpL
            aE1WejJzY2pib1ZEdytOeTdONkRNRXMKLS0tIEcwbUdJMjdwOE1IMXVwMlpGcDNW
            dVJ6bzdINUR0eG8xbzVPdkFJK043RzQKqg4eseHcQ3ZTyEaSu0X7jePMKYcEenXP
            U44v8zCIhrjlyQtQa0i+vTGTlXZyVvQUP7+si9WrHoxK7u9rj3kU1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:27:20Z"
    mac: ENC[AES256_GCM,data:EhJWK+cTDquHWO7azWIKfYUl9xttxnVS0olgE0zMcbL+HSKUtBJG/rWlzPSnSXb+AaKcBHrer0Q1a0MmtgEQ2HJkcfD+9/f5HjlKThWKptYtnY6Ly7nF1xUdyl+7SaWjvc1mZoXvJu1BIzoE5YK/DiMdUAtFRZGffHqaERrz3Vw=,iv:mu4vf088+/Y/69UnWCymT7FAqzeERADL1lOGHMLKszA=,tag:jC5z1fk22HTuymXIOO0Zvw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
