apiVersion: v1
kind: ConfigMap
metadata:
    name: nextcloud-configs
    namespace: nextcloud
data:
    values.yaml: ENC[AES256_GCM,data:EvxaAG6p8O5osqKFlGnW0MWfxjvJjUATYLyYT0bUT4KKRR+doPVk3EWXrg6ULlEOdgaUrBUwMBEWnNbxHDsk2UiTXxiG4ZyqTG7WJqjhq2zK+QiDcRBckhm6az7kvscCZTgVYD1pD6xBB2QZUxaDfu3bXXc46zNKwT8iWZtJWdzs6wlNqr8PIzCXdjvajz6bwP9ysAy39F/Rt19iQRGr3doFa89jyVuxrMR6feFT6aNAOKnut8H92vxotQA2MUY8Sp/9sg60w3Obj2QQSzmqwG6dpRPoaE0+N0vYFvSNq4fsxZTKzOP3JzeKIFLfYDD5Z0WesRgurcdiHs5druQcRMlLBDGXbVTzweo74yRQP1Bzld64lmucHe6776XrQ6Io5bMMNqwDfHL/x4CJYVv37QxZ6MtsYoguxL66KGwQPC8KthD8b6NoHA7fvtEDjBuSKsJMbktGbmvReQGV9IoGqs8TWIbAZc05F98e1H17oKe8w0TwuBE9k6o20pP3GxFFbpEP/rf0XnITUG4x4/uaCNUOgHNE6CHye5GSbNqUF6DwkjnNf4XT3cJQySVCr7LmpTzzdW9ca5lIbDTlTbluKr2Mz0XrCX5hNaWx7AV+h3AiJxbYxcjlqm1XiE5Kzjid8ebZsrVcBu/YfaKHFs8sjAEGyQLmxE8QN/aA2RTRrALS2HwAE3tjKuWq9nrVVmkN7AGQ/vBPLgzfrjJeNaPRECU4U3FpnLNrUXthqE4Zb7Yqyib04xXM/JATFu5iATFInvOz+GRQQgg7q7KRkdxLK8dI630U1dccbh4OIjXkQcirqMyu0ss8b9uNH6IdJwAhL4FiV87EM8+m5bQJ2yCOkLkt/KeR/jhuAy8eczv905DvWCAZ8ITZZQckIme99Cbiz2w4jdfzZ/L/a+3ReN5+u6rUkiMq7rb1IHbfC6r3YXdtpp5Kaa6g70RuDWIHJvIMRjosE+sBmRH1mm1uR80tVbgHPisFSj2gqGnrDjDODPx8O0WEr7GJ+2UEnnAXwLlEMpNIQg==,iv:IZdQz+ThPT00q81Z7fan5nMKKw9AVwTATtaPzqtMl6A=,tag:Vm8UVUihvsisrn4csYpWyQ==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGJmQlc0YjZsN1hJSmdL
            T0wwbWk0WkxWVVdxRVo5dW1CYkVHSzU2bHl3Ck10ZlRTdkNsNDFLb0JYNDVJQmpL
            aE1WejJzY2pib1ZEdytOeTdONkRNRXMKLS0tIEcwbUdJMjdwOE1IMXVwMlpGcDNW
            dVJ6bzdINUR0eG8xbzVPdkFJK043RzQKqg4eseHcQ3ZTyEaSu0X7jePMKYcEenXP
            U44v8zCIhrjlyQtQa0i+vTGTlXZyVvQUP7+si9WrHoxK7u9rj3kU1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T20:38:25Z"
    mac: ENC[AES256_GCM,data:CLDV3QkV43wpbP2kBUjUkZZTvlGd5pjdvf/UifRPLQCaRuzb5337Ezv2z8GYGtGcvyqaGAS+wEajOFfoBhIRPUWjfZOELGJbdxEMbY1AHwgB8GqgDoRbOl79CZQrrs5uQpRmA+OtK2uQ9sSxPdCak1dO6V6C24l0rQ9R+kEthuc=,iv:4N0eXr6U0VIIu2sxF62ow9XoiXLcKxpVyqAv6MA62Gs=,tag:Qc0HES4vFXHk8ubF+gmvfw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
