apiVersion: v1
kind: ConfigMap
metadata:
    name: nextcloud-configs
    namespace: nextcloud
data:
    values.yaml: ENC[AES256_GCM,data:B2sd0LLC22CYXhGJ2q3iEKB8LIltpkJkbRR+W2yoM9kR6vqJNApHEIIwjrC5ULWTnWn0VU6v8Hi0vw7ALiagm4M54phfSFLXzyMZ4w5DOUQWKBrEOBPfNmY2VfN/4zoniwoo1Xfwx2AQcx/EPfM1uWzW0yU/Dy5N2FwspF6FvRXyr9/nqygS+UxaignJQQ3P9XxPGSaLkmTSqeGwkz2aTdst4KGxEpV6gAFDuAsgglyamvDuTmt7k2UvCX8axCK9XhCfoKroqH1Mb90nEw7TXl0l8xKUKMxpwWzSsD6qOurpNouYocszAmGH2B80XIL4qkgzmde/4yI92QsuxIxHv6795AbLJjmsrva1fEh4PQkVaT+HuhoWNhmD05YZHKG9Fu43evGqIcAcRVjvR7Ig16LhlSgjYhWWQCacYsKzmekIjpZWtXR3r+NTlxLcQX6XOT8e/XyaJDuRuwiXKUzI7vkOF8K4gDTdTcpg8A+/fs+5PkS+UD0YXAhQigc01v0RxhFLCdApUPm5NYasCMTT4sUxH0KJaaWseDZjyzVunGsmBZ9WItAoFibPX2Y+euyxW1kQmgUeI4tGjb5LGbDRm4AC0Ht6dfsNvZppA1s2AN92CNsxuIwex/JrKEjY8NQpnqc+2nYkK4ptejGPGCsiKwEhhxezDWT/9kC5EebdXVci0rhzt9uH6m4ya3jxtlQd1qfuhIJgPoksxHbwQy1jKhYoN+EroY86azuo0XdxBkXT733M7GOdXLZArstZQdiJ2Ff0dLdFngwLUE+2uS+1vkPYhyvmX/eQwfO0KUCAbtOPUqay+cUvXEu8MZjubvGMiuE=,iv:EoJv3BKoaTNuqU9L2BcbGJK0GChFesU5s1w2U83QL6s=,tag:JzjPNAuibw6i7AwdCI1l2A==,type:str]
sops:
    age:
        - recipient: age1r0y2hakc227f26hlnuhsk6pfuy7qauqy2ak2ntwwjdpr4q6fuvuqdk8kpq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGJmQlc0YjZsN1hJSmdL
            T0wwbWk0WkxWVVdxRVo5dW1CYkVHSzU2bHl3Ck10ZlRTdkNsNDFLb0JYNDVJQmpL
            aE1WejJzY2pib1ZEdytOeTdONkRNRXMKLS0tIEcwbUdJMjdwOE1IMXVwMlpGcDNW
            dVJ6bzdINUR0eG8xbzVPdkFJK043RzQKqg4eseHcQ3ZTyEaSu0X7jePMKYcEenXP
            U44v8zCIhrjlyQtQa0i+vTGTlXZyVvQUP7+si9WrHoxK7u9rj3kU1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T00:28:47Z"
    mac: ENC[AES256_GCM,data:PmfqBQs6FxswrtaIEeVuFI/jRVy6lMmHL14ZmbCBHoOKlU1lVIwOmN4oeoI+4b6sEJDh+ibbYLeoTOqVMF5iDIrMx7BZVbbXi5Lx2BqY8Y2jQTudpThHx3VRtMdBeDCJQxD8UKdoECqUBt2OZmSkaMprPyNqxwdK20mk7qB1V1E=,iv:CvKGrNP3UkXUhrc/Y1NOZfEyFCONSqwsBzNg4aI6LLM=,tag:qUUsSKFaWs478WoV+V2LGg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
