apiVersion: v2
name: hashtopolis
description: "A Helm chart for Hashtopolis - distributed password recovery platform"
type: application
version: 0.1.0
appVersion: "v0.14.3"
kubeVersion: '>=1.24.0-0'
dependencies:
  - name: common
    version: 28.26.0
    repository: oci://tccr.io/truecharts
