apiVersion: v1
kind: Service
metadata:
  name: portainer-external
  namespace: web-services
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: portainer-external
  namespace: web-services
subsets:
  - addresses:
      - ip: 192.168.1.65
    ports:
      - name: https
        port: 9443
        protocol: TCP
