apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - clustersettings.secret.yaml
  - default
  - flux-entry.yaml
  - development
  - games
  - gitlab
  - home
  - infrastructure
  - kube-system
  - media
  - mirrors
  - nextcloud
  - storage
  - system
  - torrents
  - web-services
